[package]
name = "cargo-unleash"
version = "0.1.0-git"
authors = ["Benjamin Kampmann <ben@gnunicorn.org>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
cargo = "0.42.0"
semver = "0.9.0"
structopt = "0.3.9"
toml_edit = "0.1.3"
log = "0.4.8"
flexi_logger = "0.14.8"
petgraph = "0.5.0"