[package]
name = "cargo-unleash"
version = "1.0.0-alpha.3"
authors = ["Benjamin Kampmann <ben@gnunicorn.org>"]
edition = "2018"
license = "GPL-3.0"
repository ="https://github.com/gnunicorn/cargo-unleash"
description = "Tooling to manage releasing of crates in massiv workspaces/monorepos"

[[bin]]
name = "cargo-unleash"
path = "src/main.rs"

[dependencies]
structopt = "0.3.9"
toml_edit = "0.1.3"
log = "0.4.8"
flexi_logger = "0.14.8"
petgraph = "0.5.0"
regex = "1.3.4"

# CARGO VERSION BOUND dependencies
cargo = "0.42.0"
semver = "0.9.0"
flate2 = "1.0.3"
failure = "0.1.5"
tar = "0.4.18"
